name: Build and Patch

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
      MU3_REFERENCE_REPO:
        required: true
      MU3_REFERENCE_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash
        working-directory: mu3-optimizer

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: mu3-optimizer

      - name: Checkout Mu3Reference
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MU3_REFERENCE_REPO }}
          token: ${{ secrets.MU3_REFERENCE_PAT }}
          path: mu3-reference

      - name: Install native cross compiler
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-mingw-w64-x86-64
          rustup target add x86_64-pc-windows-gnu

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Build assemblies and patches
        timeout-minutes: 30
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: ./build.sh all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Steroid.mm
          path: |
            mu3-optimizer/bin/Release/net35/Assembly-CSharp.Steroid.mm.dll
            mu3-optimizer/bin/Release/net35/AMDaemon.NET.Steroid.mm.dll
            mu3-optimizer/bin/Release/net35/MONOMODDED_Assembly-CSharp.dll
            mu3-optimizer/bin/Release/net35/MONOMODDED_AMDaemon.NET.dll
