name: Build and Patch

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
        working-directory: mu3-optimizer

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: mu3-optimizer

      - name: Checkout Mu3Reference
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MU3_REFERENCE_REPO }}
          token: ${{ secrets.MU3_REFERENCE_PAT }}
          path: mu3-reference

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build Steroid.sln -c Release

      - name: Run MonoMod
        run: |
          cd bin/Release/net35
          ./MonoMod.exe Assembly-CSharp.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Steroid.mm
          path: |
            mu3-optimizer/bin/Release/net35/Assembly-CSharp.Steroid.mm.dll
            mu3-optimizer/bin/Release/net35/AMDaemon.NET.Steroid.mm.dll
